name: Sonar
on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"
      test-database:
        required: false
        type: boolean
        default: false
  workflow_run:
    workflows: [CI shared workflow]
    types: [completed]
permissions:
  # SonarCloud needs write permissions to write the analysis results
  # to the comment of the PR. Hardener might complain that this should
  # be read
  contents: write

jobs:
  Sonar:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      
      - name: Harden Runner
        uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.0
        # ony on public repos
        if: ${{ !github.event.repository.private }}
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            analysis-sensorcache-eu-central-1-prod.s3.amazonaws.com:443
            api.github.com:443
            api.sonarcloud.io:443
            binaries.sonarsource.com:443
            *.execute-api.eu-central-1.amazonaws.com:443
            github.com:443
            sc-cleancode-sensorcache-eu-central-1-prod.s3.amazonaws.com:443
            scanner.sonarcloud.io:443
            sonarcloud.io:443
          
          
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0
      - name: Get run ID of parent CI workflow
        id: get-run-id
        run: |
          OTHER_REPO="${{ github.repository }}"
          WF_NAME="CI"
          RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId --jq .[0].databaseId`
          echo "Detected latest run id of ${RUN_ID} for workflow ${WF_NAME}"
          echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Download artifact from CI workflow
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report-${{ inputs.python-version }}
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get-run-id.outputs.run-id }}
      - uses: actions/download-artifact@v4
        if: ${{ inputs.test-database }}
        with:
          name: code-coverage-postgres-report-${{ inputs.python-version }}
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get-run-id.outputs.run-id }}
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.scm.revision=${{ github.event.workflow_run.head_sha }}
            -Dsonar.pullrequest.key=${{ github.event.workflow_run.pull_requests[0].number }}
            -Dsonar.pullrequest.branch=${{ github.event.workflow_run.pull_requests[0].head.ref }}
            -Dsonar.pullrequest.base=${{ github.event.workflow_run.pull_requests[0].base.ref }}
